# Generated by Django 3.2.5 on 2021-07-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('received', models.DateTimeField(auto_now_add=True, verbose_name='Receive datetime')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Notification message')),
                ('sender_ip', models.CharField(blank=True, max_length=256, null=True, verbose_name='Значение свойства')),
            ],
        ),
    ]
