# Generated by Django 3.2.5 on 2021-08-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testservice', '0003_auto_20210730_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backend',
            old_name='parameters',
            new_name='settings',
        ),
    ]
