# Generated by Django 3.2.5 on 2021-08-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testservice', '0004_rename_parameters_backend_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='classname',
            field=models.CharField(default='GenericBackendInterface', max_length=255, verbose_name='Backend name'),
        ),
    ]
